#设置项目名称
spring: 
  application: 
    name: jaray-register-center
  security: 
   user: 
     name: admin
     password: 123456
    
#设置项目端口
server: 
  port: 8762
  
eureka: 
  server: 
    peer-node-read-timeout-ms: 1000 #SocketTimeoutException: Read timed out
  instance: 
    hostname: 127.0.0.1
    appname: ${spring.application.name}
    # 使用ip地址注册到eureka server(神坑---unavailable-replicas)
    #prefer-ip-address: true
    # 在eureka server中看到的status显示为具体的ip地址和port
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 注册给eureka的时候告诉eureka自己的密码
    metadata-map: 
      "user.name": ${spring.security.user.name}         #These two are needed so that the server
      "user.password": ${spring.security.user.password} #can access the protected client endpoints
  client: 
    register-with-eureka: false
    fetch-registry: false
    #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址，多个地址可使用 ，分隔。
    service-url: 
      defaultZone: http://localhost:8761/eureka/,http://127.0.0.1:8762/eureka/

# 2.0开始，actuator默认不开放，所以要设置为开放
management: 
  endpoints: 
    web: 
      exposure: 
        include: "*"
  endpoint: 
    health: 
      show-details: ALWAYS