#配置端口
server: 
  port: 8001
#配置服务名
spring:
  application:
    name: jaray-scheduled-shedlock
# 配置MYSQL DRUID数据源
  datasource: 
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid: 
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/jaray-schedule-quartz?serverTimezone=GMT%2B8&useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
      username: root
      password: root
      filters: stat,wall,slf4j,config                           #配置监控统计拦截的filters，去掉后监控界面SQL无法进行统计，’wall’用于防火墙
      max-active: 100                                           #最大连接数
      initial-size: 5                                           #初始化大小
      max-wait: 60000                                           #获取连接等待超时时间
      min-idle: 1                                               #最小连接数 
      time-between-eviction-runs-millis: 60000                  #间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000                    #一个连接在池中最小生存的时间，单位是毫秒
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
        
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.example.demo: DEBUG

#配置注册中心
eureka:
  instance: 
    # 使用ip地址注册到eureka server
    prefer-ip-address: true  
    # 在eureka server中看到的status显示为具体的ip地址和port(在此设置随机端口)
    instance-id: ${spring.cloud.client.ip-address}:${server.port} 
    
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health   #2.0以后actuator的地址发生了变化
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    service-url: 
      defaultZone: http://localhost:8761/eureka/,http://127.0.0.1:8762/eureka/