#配置端口
#server: 
#  port: 7001
#配置服务名
spring:
  application:
    name: service-provider-one
    
#配置注册中心
eureka:
  instance: 
    # 使用ip地址注册到eureka server
    prefer-ip-address: true  
    # 在eureka server中看到的status显示为具体的ip地址和port(在此设置随机端口)
    instance-id: ${spring.cloud.client.ip-address}:${server.port} 
    
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health   #2.0以后actuator的地址发生了变化
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    service-url: 
      defaultZone: http://localhost:8761/eureka/

# 2.0开始，actuator默认不开放，所以要设置为开放
management: 
  endpoints: 
    web: 
      exposure: 
        include: "*"
  endpoint: 
    health: 
      show-details: ALWAYS
    
